export const SET_HASHED_PACKAGES_TYPE = 'SET_HASHED_PACKAGES';

export const SET_REPOSITORY_SELECTION_TYPE = 'SET_REPOSITORY_SELECTION';

export const SET_RESULTS_TYPE = 'SET_RESULTS';

export const SET_SESSION_ID_TYPE = 'SET_SESSION_ID';

export const SET_TECHNOLOGY_SELECTION_TYPE = 'SET_TECHNOLOGY_SELECTION';

export const SET_UPLOADED_PACKAGES_TYPE = 'SET_UPLOADED_PACKAGES';

export const ITEMS_HAS_ERRORED_TYPE = 'ITEMS_HAS_ERRORED';

export const ITEM_LOADING_TYPE = 'ITEM_LOADING';

export const ITEM_STOPPED_LOADING_TYPE = 'ITEM_STOPPED_LOADING';

export const SET_PROCESS_RESULTS_TYPE = 'SET_PROCESS_RESULTS';

export const DUPLICATION_FETCH_TYPE = 'DUPLICATION_FETCH';

export const REPOSITORY_UPLOAD_FETCH_TYPE = 'REPOSITORY_UPLOAD_FETCH';

export const UPLOAD_TO_STORAGE_FETCH_TYPE = 'UPLOAD_TO_STORAGE_FETCH';

export const CREATE_STORAGE_BUCKET_FETCH_TYPE = 'CREATE_STORAGE_BUCKET_FETCH';

export const DEPENDENCY_FETCH_TYPE = 'DEPENDENCY_FETCH';
